source: src
destination: dist
languages: ["en", "de"]
collections_dir: collections
exclude_from_localizations: ["assets", "javascript", "images", "css"]

plugins:
  - jekyll-multiple-languages-plugin

collections:
  - diagnoses
  - specialties