source: src
destination: dist
languages: ["de", "en"]
collections_dir: collections
exclude: ["assets/javascripts", "assets/stylesheets"]
keep_files: ["assets/javascripts", "assets/stylesheets"]
exclude_from_localizations: ["assets", "javascript", "images", "css"]

plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-twitter-plugin

collections:
  - diagnoses
  - specialties
  - testimonials