baseurl: https://www.bheidecker.com
domain: bheidecker.com
endpoint: https://europe-west3-bheidecker.cloudfunctions.net/pager

languages: ["de", "en"]
collections_dir: collections

exclude:
  - assets/javascripts
  - assets/stylesheets

keep_files:
  - .git
  - assets/javascripts
  - assets/stylesheets

exclude_from_localizations:
  - assets
  - CNAME

plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-twitter-plugin

collections:
  - diagnoses
  - specialties
  - testimonials