domain: bheidecker.github.io
url: https://bheidecker.github.io
baseurl: /bettini/

languages: ["de", "en"]
collections_dir: collections
exclude_from_localizations:
  - assets

plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-twitter-plugin

collections:
  - diagnoses
  - specialties
  - testimonials